version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "raktbandhan-backend"
resolve_s3 = true
s3_prefix = "raktbandhan-backend"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
